version: "3.8"
services:
  py: &py
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - USER_PRIVATE_KEY
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "32m"

