version: "3.8"
services:
  py-arbitrum-rinkeby:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - USER_PRIVATE_KEY
      - WEB3_PROVIDER_URI=https://rinkeby.arbitrum.io/rpc
      - WEB3_NETWORK_NAME=arbitrum_rinkeby
      - PERPDEX_CONTRACT_ABI_JSON_DIRPATH=/app/deps/perpdex-contract/deployments/arbitrum_rinkeby/
      - PERPDEX_MARKET=USD
      - BINANCE_SYMBOL=ETHUSDT
      - ONE_SIDE_ARB=1
    command: python main.py run
    logging:
      driver: "json-file"
      options:
        max-size: "32m"
    restart: always
