version: "3.8"
services:
  py: &py
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - USER_PRIVATE_KEY
      - WEB3_PROVIDER_URI
      - WEB3_NETWORK_NAME
      - PERPDEX_CONTRACT_ABI_JSON_DIRPATH
      - BINANCE_API_KEY
      - BINANCE_SECRET
      - BYBIT_API_KEY
      - BYBIT_SECRET
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "32m"

  py-test:
    <<: *py
    environment:
      - USER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - WEB3_PROVIDER_URI=http://perpdex-hardhat:8545
      - WEB3_NETWORK_NAME=localhost
      - PERPDEX_CONTRACT_ABI_JSON_DIRPATH=/app/hardhat/deployments/localhost/
      - BINANCE_API_KEY
      - BINANCE_SECRET
      - BYBIT_API_KEY
      - BYBIT_SECRET
    depends_on:
      - perpdex-hardhat

  perpdex-hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    volumes:
      - ./hardhat:/app
      - ./deps:/deps
    command: sh -c "yarn install && yarn hardhat node"
    expose:
      - 8545  # hardhat localhost default port

volumes:
  unmount_vol:
